version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: mq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # UI de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: ./app
    container_name: app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
