version: "3.9"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - MINIO_ENDPOINT=http://172.17.0.1:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=videos
    ports:
      - "8000:8000"
    depends_on:
      - minio

volumes:
  minio-data:
